config/routes.rb
Rails.application.routes.draw do
  resources :quizzes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'quiz#index'
  
  get 'quiz/index'
  
  post 'quiz', to:'quiz#req'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quiz.rb
class Quiz < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quiz_controller.rb
require 'net/http'
require_relative '../services/pushkin'

class QuizController < ApplicationController
  skip_before_action :verify_authenticity_token  
  FILE_PUSH_POEMS = FilePushkin.new.parse

  def index 
    
  end

  def req
    
  case params[:level].to_i

    when 1
      answer = level_1(params[:question])
    when 2
      answer = level_2(params[:question])[0]
    when 3
      answer = level_3(params[:question])
    when 4
      answer = level_4(params[:question])
    when 5
      answer = level_5(params[:question])
    when 6
      answer = level_6_7(params[:question])
    when 7
      answer = level_6_7(params[:question])
    when 8
      answer = level_8(params[:question])
    end

    uri = URI("http://pushkin.rubyroidlabs.com/quiz")
    parameters = {
      answer: answer,
      token: "89e4fd81545ad22932910f14583d1ef4",
      task_id: params[:id]
    }
    Net::HTTP.post_form(uri, parameters)

  end

  private

  def level_1(question)
    question = delete_excess(question)

    FILE_PUSH_POEMS.each do |poem|
      poem[1].each do |line|
        line = delete_excess(line)
        return poem[0] if line == question
      end
    end
  end

  def level_2(question)
    parts = question.split('%')

    FILE_PUSH_POEMS.each do |poem|
      poem[1].each do |line|
        if line.include? parts[0]
          return line.split(' ') - question.split(' ')
        end
      end
    end   
  end

  def level_3(question)
    parts = question.split("\n")
    first_str = parts[0].split('%')
    
    FILE_PUSH_POEMS.each do |poem|
      poem[1].each do |line|
        if line.include? first_str[0]
          word_1 =  line.split(' ') - parts[0].split(' ')
          index_1 = poem[1].index(line)           
          index_2 =  poem[1][index_1 + 1]
          word_2 = index_2.split(' ') - parts[1].split(' ')
          @last_str = "#{word_1[0]},#{word_2[0]}"
          break
        end       
      end
    end
    return @last_str
  end

  def level_4(question)
    parts = question.split("\n")
    first_str = parts[0].split('%')
    
    FILE_PUSH_POEMS.each do |poem|
      poem[1].each do |line|
        if line.include? first_str[0]
          word_1 =  line.split(' ') - parts[0].split(' ')
          index_1 = poem[1].index(line)           
          index_2 =  poem[1][index_1 + 1]
          index_3 = poem[1][index_1 + 2]
          word_2 = index_2.split(' ') - parts[1].split(' ')
          word_3 = index_3.split(' ') - parts[2].split(' ')
          @last_str = "#{word_1[0]},#{word_2[0]},#{word_3[0]}"
          break
        end       
      end
    end
    return @last_str
  end

  def level_5(question)
    parts = question.split(' ')

    FILE_PUSH_POEMS.each do |poem|
      poem[1].each do |line|
        if line.include? parts[0]
          word_1 = line.split(' ') - question.split(' ')
          word_2 = question.split(' ') - line.split(' ')
          @str = "#{word_1[0]},#{word_2[0]}"
          break
        end
      end
    end
    return @str
  end

  def level_6_7(question)
    parts = question.split('')
    
    FILE_PUSH_POEMS.each do |poem|
      poem[1].each do |line|
        letters = delete_excess(line).split('')
        if parts - letters == []
          return line
        end
      end
    end
  end 
  
  def level_8(question)
    parts = question.split('')

    FILE_PUSH_POEMS.each do |poem|
      poem[1].each do |line|
        letters = delete_excess(line).split('')
        tmp = letters - parts
        sum = parts + letters
        last_str = sum.uniq
        last_str.pop
        last_str += tmp
        if last_str - letters == []
          return line 
        end
      end
    end
  end

  def delete_excess(str)
    return str.gsub(/[,?.!:+-=*_@#()^;№'<>~`«»—]/, '')
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]

  # GET /quizzes
  # GET /quizzes.json
  def index
    @quizzes = Quiz.all
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to @quiz, notice: 'Quiz was successfully created.' }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: 'Quiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: 'Quiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      params.require(:quiz).permit(:question, :task_id, :level, :decimal, :answer)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PushkinContestBot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quiz/index.html.erb
<h1>hello</h1>
Sorry, but I don't have enough time to do history.

app/views/quizzes/_form.html.erb
<%= form_with(model: quiz, local: true) do |form| %>
  <% if quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question %>
    <%= form.text_field :question %>
  </div>

  <div class="field">
    <%= form.label :task_id %>
    <%= form.text_field :task_id %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.text_field :level %>
  </div>

  <div class="field">
    <%= form.label :decimal %>
    <%= form.text_field :decimal %>
  </div>

  <div class="field">
    <%= form.label :answer %>
    <%= form.text_field :answer %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quizzes/edit.html.erb
<h1>Editing Quiz</h1>

<%= render 'form', quiz: @quiz %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

app/views/quizzes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quizzes</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Task</th>
      <th>Level</th>
      <th>Decimal</th>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td><%= quiz.question %></td>
        <td><%= quiz.task_id %></td>
        <td><%= quiz.level %></td>
        <td><%= quiz.decimal %></td>
        <td><%= quiz.answer %></td>
        <td><%= link_to 'Show', quiz %></td>
        <td><%= link_to 'Edit', edit_quiz_path(quiz) %></td>
        <td><%= link_to 'Destroy', quiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quiz', new_quiz_path %>

app/views/quizzes/new.html.erb
<h1>New Quiz</h1>

<%= render 'form', quiz: @quiz %>

<%= link_to 'Back', quizzes_path %>

app/views/quizzes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @quiz.question %>
</p>

<p>
  <strong>Task:</strong>
  <%= @quiz.task_id %>
</p>

<p>
  <strong>Level:</strong>
  <%= @quiz.level %>
</p>

<p>
  <strong>Decimal:</strong>
  <%= @quiz.decimal %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @quiz.answer %>
</p>

<%= link_to 'Edit', edit_quiz_path(@quiz) %> |
<%= link_to 'Back', quizzes_path %>